[pytest]
pythonpath = . src
addopts = -p no:cacheprovider
env_files =
    .env.test
env_override_existing_values = 1
asyncio_mode = auto
norecursedirs =
    .git
    .venv
    .pytest_cache
    pytest-cache-files-*
filterwarnings =
    ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning:starlette.formparsers
    ignore:'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning:fastapi.routing
    ignore:'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning:starlette._utils
